root: '/problems'
competition: '2020'
name: 'signal_of_hope'
files:
  - src: 'signal_of_hope'
    dest: 'signal_of_hope'
    mode: 2555
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
xinetd:
    port: 20202
    server: "signal_of_hope"
