root: "/problems"
competition: "2020"
name: "inputter"
files:
  - src: "inputter"
    dest: "inputter"
    mode: 2555
  - src: "inputter.c"
    dest: "inputter.c"
    mode: 444
  - src: "flag.txt"
    dest: "flag.txt"
    mode: 440
