root: '/problems'
competition: '2020'
name: 'califrobnication'
files:
  - src: 'califrobnication'
    dest: 'califrobnication'
    mode: 2555
  - src: 'califrobnication.c'
    dest: 'califrobnication.c'
    mode: 444
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
