root: '/problems'
competition: '2021'
name: 'stickystacks'
files:
  - src: 'stickystacks'
    dest: 'stickystacks'
    mode: 2555
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
  - src: 'stickystacks.c'
    dest: 'stickystacks.c'
    mode: 444
xinetd:
  port: 21820
  server: 'stickystacks'
