FROM mariadb
ENV MYSQL_ROOT_PASSWORD=hHalkjsdfopfi1-02940utiohjkewibuijnigua09sd8f76880912i3ojh280wtg7auhdjknklasdjfbnfmka;ki098))*%(&Y*9i1jkl382u34*)&uoij
ENV MYSQL_USER=actf2020
ENV MYSQL_PASSWORD=thenamesbondionicbonddundun
ENV MYSQL_DATABASE=AgentsDB

LABEL options='{"network":"agents-2020", "name":"agents-mysql"}'

COPY setup.sql /docker-entrypoint-initdb.d/setup.sql
