root: '/problems'
competition: '2021'
name: 'float_on'
files:
  - src: 'float_on'
    dest: 'float_on'
    mode: 2555
  - src: 'float_on.c'
    dest: 'float_on.c'
    mode: 444
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
xinetd:
  port: 21399
  server: 'float_on'
