root: "/problems"
competition: "2021"
name: "free_flags"
files:
  - src: "free_flags"
    dest: "free_flags"
    mode: 2555
  - src: "flag.txt"
    dest: "flag.txt"
    mode: 440
xinetd:
  port: 21703
  server: "free_flags"

