root: "/problems"
competition: "2021"
name: "lockpicking"
files:
  - src: "lockpicking"
    dest: "lockpicking"
    mode: 2555
  - src: "flag.txt"
    dest: "flag.txt"
    mode: 440
xinetd:
  port: 21702
  server: "lockpicking"

