root: '/problems'
competition: '2020'
name: 'no_canary'
files:
  - src: 'no_canary'
    dest: 'no_canary'
    mode: 2555
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
  - src: 'no_canary.c'
    dest: 'no_canary.c'
    mode: 444
xinetd:
  port: 20700
  server: 'no_canary'
