root: '/problems'
competition: '2020'
name: 'bop_it'
files:
  - src: 'bop_it'
    dest: 'bop_it'
    mode: 2555
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
  - src: 'bop_it.c'
    dest: 'bop_it.c'
    mode: 444
xinetd:
  port: 20702
  server: 'bop_it'
