root: '/problems'
competition: '2019'
name: 'returns'
files:
  - src: 'returns'
    dest: 'returns'
    mode: 2555
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
  - src: 'returns.c'
    dest: 'returns.c'
    mode: 444
xinetd:
  port: 19307
  server: 'returns'
