root: "/problems"
competition: "2021"
name: "masochistic_snake"
files:
  - src: "masochistic_snake"
    dest: "masochistic_snake"
    mode: 2555
  - src: "flag.txt"
    dest: "flag.txt"
    mode: 440


