root: '/problems'
competition: '2021'
name: 'pawn'
files:
  - src: 'pawn'
    dest: 'pawn'
    mode: 2555
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
  - src: 'pawn.c'
    dest: 'pawn.c'
    mode: 444
xinetd:
  port: 21706
  server: 'pawn'
