root: '/problems'
competition: '2018'
name: 'letter'
files:
  - src: 'personal_letter32'
    dest: 'personal_letter32'
    mode: 2555
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
  - src: 'letter.c'
    dest: 'letter.c'
    mode: 444
