root: '/problems'
competition: '2020'
name: 'canary'
files:
  - src: 'canary'
    dest: 'canary'
    mode: 2555
  - src: 'flag.txt'
    dest: 'flag.txt'
    mode: 440
  - src: 'canary.c'
    dest: 'canary.c'
    mode: 444
xinetd:
  port: 20701
  server: 'canary'
